apiVersion: apps/v1
kind: Deployment
metadata:
  name: autohub-gateway
  namespace: log-analysis
  labels:
    app: autohub-gateway
    tier: public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autohub-gateway
  template:
    metadata:
      labels:
        app: autohub-gateway
        tier: public
    spec:
      imagePullSecrets:
      - name: acr-pull-secret
      containers:
      - name: gateway
        image: loganalysisregistrysrev2.azurecr.io/autohub-gateway:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: autohub-gateway-service
  namespace: log-analysis
  labels:
    app: autohub-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: autohub-gateway
